server:
  port: 8080
  servlet:
    context-path:

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=spring_app;encrypt=true;trustServerCertificate=true
    username: sa
    password: 1
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  properties:
    hibernate:
      format-sql: true
      dialect: org.hibernate.dialect.SQLServerDialect

jwt:
  secret: duongtest
  refresh-secret: duongrefreshtoken
  expiration:
    jwt: 604800000
    refresh-jwt: 1209600000